/* Generated by @deepseek-ai/dsh-typert-generator from the Host FaceModel — do not edit. */
import type {
  RemoteResult,
  TypertRemoteContribution,
} from '@deepseek-ai/dsh-typert-protocol'
import type { Config, DebugSnapshot, Envelope, GateItem, LlmOption, NodeStatus, PeerInfo, ProjectEntry } from '@rellopn/dsh-p2p-lan/types'

declare module '@deepseek-ai/dsh-typert-protocol' {
  interface TypertRemoteNamespace$703270 {
    approveGate: (id: string, finalBody?: string) => Promise<RemoteResult<{ ok: boolean; }>>
    checkInbox: () => Promise<RemoteResult<Envelope[]>>
    inboxSnapshot: () => Promise<RemoteResult<Envelope[]>>
    gateSnapshot: () => Promise<RemoteResult<Array<GateItem & { id: string; }>>>
    getProjects: () => Promise<RemoteResult<ProjectEntry[]>>
    getConfig: () => Promise<RemoteResult<Config>>
    importWorkspaces: () => Promise<RemoteResult<{ ok: boolean; added: number; }>>
    llmOptions: () => Promise<RemoteResult<LlmOption[]>>
    backgroundWaits: () => Promise<RemoteResult<Array<{ sessionId: string; count: number; }>>>
    nodeStatus: () => Promise<RemoteResult<NodeStatus>>
    debugSnapshot: () => Promise<RemoteResult<DebugSnapshot>>
    peers: () => Promise<RemoteResult<PeerInfo[]>>
    rejectGate: (id: string) => Promise<RemoteResult<{ ok: boolean; }>>
    setProjects: (projects: ProjectEntry[]) => Promise<RemoteResult<{ ok: boolean; }>>
    setConfig: (config: Config) => Promise<RemoteResult<{ ok: boolean; }>>
  }
  interface TypertRemoteMap {
    'p2p/approveGate': (id: string, finalBody?: string) => Promise<RemoteResult<{ ok: boolean; }>>
    'p2p/checkInbox': () => Promise<RemoteResult<Envelope[]>>
    'p2p/inboxSnapshot': () => Promise<RemoteResult<Envelope[]>>
    'p2p/gateSnapshot': () => Promise<RemoteResult<Array<GateItem & { id: string; }>>>
    'p2p/getProjects': () => Promise<RemoteResult<ProjectEntry[]>>
    'p2p/getConfig': () => Promise<RemoteResult<Config>>
    'p2p/importWorkspaces': () => Promise<RemoteResult<{ ok: boolean; added: number; }>>
    'p2p/llmOptions': () => Promise<RemoteResult<LlmOption[]>>
    'p2p/backgroundWaits': () => Promise<RemoteResult<Array<{ sessionId: string; count: number; }>>>
    'p2p/nodeStatus': () => Promise<RemoteResult<NodeStatus>>
    'p2p/debugSnapshot': () => Promise<RemoteResult<DebugSnapshot>>
    'p2p/peers': () => Promise<RemoteResult<PeerInfo[]>>
    'p2p/rejectGate': (id: string) => Promise<RemoteResult<{ ok: boolean; }>>
    'p2p/setProjects': (projects: ProjectEntry[]) => Promise<RemoteResult<{ ok: boolean; }>>
    'p2p/setConfig': (config: Config) => Promise<RemoteResult<{ ok: boolean; }>>
  }
  interface TypertRemoteNamespaceMap {
    'p2p': TypertRemoteNamespace$703270
  }
}

export declare const TYPERT_REMOTE: TypertRemoteContribution
export default TYPERT_REMOTE
//# sourceMappingURL=typert.remote-client.d.ts.map
