/* Generated by @deepseek-ai/dsh-typert-generator from FaceModel — do not edit. */
import { z } from 'zod'

const _rellopn_dsh_p2p_lan_p2p_approveGate_parameter_0$schema = z.string()
const _rellopn_dsh_p2p_lan_p2p_approveGate_parameter_1$schema = z.union([z.undefined(), z.string()])
const _rellopn_dsh_p2p_lan_p2p_approveGate_result$schema = z.object({
  'ok': z.boolean(),
})
const _rellopn_dsh_p2p_lan_p2p_checkInbox_result$schema = z.array(z.object({
  'id': z.string(),
  'kind': z.union([z.literal("request"), z.literal("reply"), z.literal("event")]),
  'from': z.object({
  'id': z.string(),
  'name': z.string(),
  'host': z.string().optional(),
  'port': z.number().optional(),
}),
  'to': z.object({
  'id': z.string().optional(),
  'name': z.string().optional(),
  'capability': z.string().optional(),
  'group': z.string().optional(),
  'broadcast': z.boolean().optional(),
  'project': z.string().optional(),
}),
  'replyTo': z.string().optional(),
  'body': z.string(),
  'attachment': z.object({
  'filename': z.string(),
  'size': z.number(),
  'hash': z.string(),
  'ref': z.string(),
}).optional(),
  'ts': z.number(),
  'auto': z.boolean().optional(),
  'depth': z.number().optional(),
}))
const _rellopn_dsh_p2p_lan_p2p_gateSnapshot_result$schema = z.array(z.intersection(z.object({
  'original': z.object({
  'id': z.string(),
  'kind': z.union([z.literal("request"), z.literal("reply"), z.literal("event")]),
  'from': z.object({
  'id': z.string(),
  'name': z.string(),
  'host': z.string().optional(),
  'port': z.number().optional(),
}),
  'to': z.object({
  'id': z.string().optional(),
  'name': z.string().optional(),
  'capability': z.string().optional(),
  'group': z.string().optional(),
  'broadcast': z.boolean().optional(),
  'project': z.string().optional(),
}),
  'replyTo': z.string().optional(),
  'body': z.string(),
  'attachment': z.object({
  'filename': z.string(),
  'size': z.number(),
  'hash': z.string(),
  'ref': z.string(),
}).optional(),
  'ts': z.number(),
  'auto': z.boolean().optional(),
  'depth': z.number().optional(),
}),
  'draftBody': z.string(),
}), z.object({
  'id': z.string(),
})))
const _rellopn_dsh_p2p_lan_p2p_getProjects_result$schema = z.array(z.object({
  'name': z.string(),
  'path': z.string(),
  'broadcast': z.boolean(),
}))
const _rellopn_dsh_p2p_lan_p2p_importWorkspaces_result$schema = z.object({
  'ok': z.boolean(),
  'added': z.number(),
})
const _rellopn_dsh_p2p_lan_p2p_peers_result$schema = z.array(z.object({
  'id': z.string(),
  'name': z.string(),
  'capabilities': z.array(z.string()),
  'projects': z.array(z.string()),
  'host': z.string(),
  'port': z.number(),
  'lastSeen': z.number(),
  'manual': z.boolean(),
}))
const _rellopn_dsh_p2p_lan_p2p_rejectGate_parameter_0$schema = z.string()
const _rellopn_dsh_p2p_lan_p2p_rejectGate_result$schema = z.object({
  'ok': z.boolean(),
})
const _rellopn_dsh_p2p_lan_p2p_setProjects_parameter_0$schema = z.array(z.object({
  'name': z.string(),
  'path': z.string(),
  'broadcast': z.boolean(),
}))
const _rellopn_dsh_p2p_lan_p2p_setProjects_result$schema = z.object({
  'ok': z.boolean(),
})
const _rellopn_dsh_p2p_lan_p2p_config$schema = z.object({
  'nodeName': z.string(),
  'advertisedHost': z.string(),
  'capabilities': z.array(z.string()),
  'autoDiscover': z.boolean(),
  'manualPeers': z.array(z.object({
  'name': z.string(),
  'host': z.string(),
  'port': z.number(),
})),
  'autoAccept': z.boolean(),
  'knownPeers': z.array(z.object({
  'name': z.string(),
  'host': z.string(),
  'port': z.number(),
})),
  'port': z.number(),
  'sensitivity': z.union([z.literal("lenient"), z.literal("standard"), z.literal("strict")]),
  'sendWaitTimeoutMs': z.number(),
  'provider': z.string(),
  'model': z.string(),
  'persona': z.string(),
  'projects': z.array(z.object({
  'name': z.string(),
  'path': z.string(),
  'broadcast': z.boolean(),
})),
})
const _rellopn_dsh_p2p_lan_p2p_setConfig_result$schema = z.object({
  'ok': z.boolean(),
})
const _rellopn_dsh_p2p_lan_p2p_nodeStatus_result$schema = z.object({
  'host': z.string(),
  'requestedPort': z.number(),
  'effectivePort': z.number(),
  'started': z.boolean(),
})
const _rellopn_dsh_p2p_lan_p2p_debugSnapshot_result$schema = z.object({
  'version': z.string(),
  'debug': z.boolean(),
  'nodeName': z.string(),
  'advertisedHost': z.string(),
  'requestedPort': z.number(),
  'effectivePort': z.number(),
  'started': z.boolean(),
  'frames': z.array(z.object({
  'dir': z.union([z.literal("in"), z.literal("out")]),
  'ts': z.number(),
  'json': z.string(),
})),
  'peers': _rellopn_dsh_p2p_lan_p2p_peers_result$schema,
  'outboxCount': z.number(),
  'inboxCount': z.number(),
  'gateCount': z.number(),
  'pendingWaits': z.number(),
  'outboundConnections': z.number(),
  'inboundConnections': z.number(),
})
const _rellopn_dsh_p2p_lan_p2p_llmOptions_result$schema = z.array(z.object({
  'provider': z.string(),
  'providerName': z.string(),
  'models': z.array(z.string()),
}))

const _rellopn_dsh_p2p_lan_p2p_backgroundWaits_result$schema = z.array(z.object({
  'sessionId': z.string(),
  'count': z.number(),
}))

export const TYPERT = {
  package: '@rellopn/dsh-p2p-lan',
  face: 'host',
  schemas: [
  ],
  invocations: [
    {
      id: '@rellopn/dsh-p2p-lan#p2p/approveGate',
      service: 'p2p',
      namespace: 'p2p',
      method: 'approveGate',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'id',
          wire: 'id',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@rellopn/dsh-p2p-lan#p2p/approveGate:id',
            schema: _rellopn_dsh_p2p_lan_p2p_approveGate_parameter_0$schema,
          },
        },
        {
          name: 'finalBody',
          wire: 'finalBody',
          source: 'json',
          acceptsUndefined: true,
          codec: {
            mode: 'strict',
            typeSymbol: '@rellopn/dsh-p2p-lan#p2p/approveGate:finalBody',
            schema: _rellopn_dsh_p2p_lan_p2p_approveGate_parameter_1$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@rellopn/dsh-p2p-lan#p2p/approveGate:result',
        schema: _rellopn_dsh_p2p_lan_p2p_approveGate_result$schema,
      },
      sourceLocation: {"file":"src/plugin.ts","line":195,"column":9},
    },
    {
      id: '@rellopn/dsh-p2p-lan#p2p/checkInbox',
      service: 'p2p',
      namespace: 'p2p',
      method: 'checkInbox',
      invocation: { kind: 'direct' },
      parameters: [
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@rellopn/dsh-p2p-lan#p2p/checkInbox:result',
        schema: _rellopn_dsh_p2p_lan_p2p_checkInbox_result$schema,
      },
      sourceLocation: {"file":"src/plugin.ts","line":185,"column":3},
    },
    {
      id: '@rellopn/dsh-p2p-lan#p2p/inboxSnapshot',
      service: 'p2p',
      namespace: 'p2p',
      method: 'inboxSnapshot',
      invocation: { kind: 'direct' },
      parameters: [
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@rellopn/dsh-p2p-lan#p2p/inboxSnapshot:result',
        schema: _rellopn_dsh_p2p_lan_p2p_checkInbox_result$schema,
      },
      sourceLocation: {"file":"src/plugin.ts","line":1,"column":1},
    },
    {
      id: '@rellopn/dsh-p2p-lan#p2p/gateSnapshot',
      service: 'p2p',
      namespace: 'p2p',
      method: 'gateSnapshot',
      invocation: { kind: 'direct' },
      parameters: [
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@rellopn/dsh-p2p-lan#p2p/gateSnapshot:result',
        schema: _rellopn_dsh_p2p_lan_p2p_gateSnapshot_result$schema,
      },
      sourceLocation: {"file":"src/plugin.ts","line":190,"column":3},
    },
    {
      id: '@rellopn/dsh-p2p-lan#p2p/getProjects',
      service: 'p2p',
      namespace: 'p2p',
      method: 'getProjects',
      invocation: { kind: 'direct' },
      parameters: [
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@rellopn/dsh-p2p-lan#p2p/getProjects:result',
        schema: _rellopn_dsh_p2p_lan_p2p_getProjects_result$schema,
      },
      sourceLocation: {"file":"src/plugin.ts","line":207,"column":3},
    },
    {
      id: '@rellopn/dsh-p2p-lan#p2p/importWorkspaces',
      service: 'p2p',
      namespace: 'p2p',
      method: 'importWorkspaces',
      invocation: { kind: 'direct' },
      parameters: [
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@rellopn/dsh-p2p-lan#p2p/importWorkspaces:result',
        schema: _rellopn_dsh_p2p_lan_p2p_importWorkspaces_result$schema,
      },
      sourceLocation: {"file":"src/plugin.ts","line":218,"column":9},
    },
    {
      id: '@rellopn/dsh-p2p-lan#p2p/peers',
      service: 'p2p',
      namespace: 'p2p',
      method: 'peers',
      invocation: { kind: 'direct' },
      parameters: [
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@rellopn/dsh-p2p-lan#p2p/peers:result',
        schema: _rellopn_dsh_p2p_lan_p2p_peers_result$schema,
      },
      sourceLocation: {"file":"src/plugin.ts","line":180,"column":3},
    },
    {
      id: '@rellopn/dsh-p2p-lan#p2p/rejectGate',
      service: 'p2p',
      namespace: 'p2p',
      method: 'rejectGate',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'id',
          wire: 'id',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@rellopn/dsh-p2p-lan#p2p/rejectGate:id',
            schema: _rellopn_dsh_p2p_lan_p2p_rejectGate_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@rellopn/dsh-p2p-lan#p2p/rejectGate:result',
        schema: _rellopn_dsh_p2p_lan_p2p_rejectGate_result$schema,
      },
      sourceLocation: {"file":"src/plugin.ts","line":201,"column":3},
    },
    {
      id: '@rellopn/dsh-p2p-lan#p2p/setProjects',
      service: 'p2p',
      namespace: 'p2p',
      method: 'setProjects',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'projects',
          wire: 'projects',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@rellopn/dsh-p2p-lan#p2p/setProjects:projects',
            schema: _rellopn_dsh_p2p_lan_p2p_setProjects_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@rellopn/dsh-p2p-lan#p2p/setProjects:result',
        schema: _rellopn_dsh_p2p_lan_p2p_setProjects_result$schema,
      },
      sourceLocation: {"file":"src/plugin.ts","line":212,"column":9},
    },
    {
      id: '@rellopn/dsh-p2p-lan#p2p/getConfig',
      service: 'p2p',
      namespace: 'p2p',
      method: 'getConfig',
      invocation: { kind: 'direct' },
      parameters: [
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@rellopn/dsh-p2p-lan#p2p/getConfig:result',
        schema: _rellopn_dsh_p2p_lan_p2p_config$schema,
      },
      sourceLocation: {"file":"src/plugin.ts","line":1,"column":1},
    },
    {
      id: '@rellopn/dsh-p2p-lan#p2p/setConfig',
      service: 'p2p',
      namespace: 'p2p',
      method: 'setConfig',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'config',
          wire: 'config',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@rellopn/dsh-p2p-lan#p2p/setConfig:config',
            schema: _rellopn_dsh_p2p_lan_p2p_config$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@rellopn/dsh-p2p-lan#p2p/setConfig:result',
        schema: _rellopn_dsh_p2p_lan_p2p_setConfig_result$schema,
      },
      sourceLocation: {"file":"src/plugin.ts","line":1,"column":1},
    },
    {
      id: '@rellopn/dsh-p2p-lan#p2p/nodeStatus',
      service: 'p2p',
      namespace: 'p2p',
      method: 'nodeStatus',
      invocation: { kind: 'direct' },
      parameters: [
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@rellopn/dsh-p2p-lan#p2p/nodeStatus:result',
        schema: _rellopn_dsh_p2p_lan_p2p_nodeStatus_result$schema,
      },
      sourceLocation: {"file":"src/plugin.ts","line":1,"column":1},
    },
    {
      id: '@rellopn/dsh-p2p-lan#p2p/debugSnapshot',
      service: 'p2p',
      namespace: 'p2p',
      method: 'debugSnapshot',
      invocation: { kind: 'direct' },
      parameters: [
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@rellopn/dsh-p2p-lan#p2p/debugSnapshot:result',
        schema: _rellopn_dsh_p2p_lan_p2p_debugSnapshot_result$schema,
      },
      sourceLocation: {"file":"src/plugin.ts","line":1,"column":1},
    },
    {
      id: '@rellopn/dsh-p2p-lan#p2p/llmOptions',
      service: 'p2p',
      namespace: 'p2p',
      method: 'llmOptions',
      invocation: { kind: 'direct' },
      parameters: [
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@rellopn/dsh-p2p-lan#p2p/llmOptions:result',
        schema: _rellopn_dsh_p2p_lan_p2p_llmOptions_result$schema,
      },
      sourceLocation: {"file":"src/plugin.ts","line":1,"column":1},
    },
    {
      id: '@rellopn/dsh-p2p-lan#p2p/backgroundWaits',
      service: 'p2p',
      namespace: 'p2p',
      method: 'backgroundWaits',
      invocation: { kind: 'direct' },
      parameters: [
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@rellopn/dsh-p2p-lan#p2p/backgroundWaits:result',
        schema: _rellopn_dsh_p2p_lan_p2p_backgroundWaits_result$schema,
      },
      sourceLocation: {"file":"src/plugin.ts","line":1,"column":1},
    },
  ],
  model: {
    "services": [
      {
        "description": "The composed P2P node, provided as `ctx.p2p` and remoted to the client as `remote.p2p`.",
        "summary": "The composed P2P node, provided as `ctx.p2p` and remoted to the client as `remote.p2p`.",
        "tags": [],
        "jsDoc": "/** The composed P2P node, provided as `ctx.p2p` and remoted to the client as `remote.p2p`. */",
        "key": "p2p",
        "exportName": "P2PService",
        "members": [
          {
            "kind": "property",
            "name": "identity",
            "signature": "readonly identity: NodeIdentity"
          },
          {
            "kind": "property",
            "name": "discovery",
            "signature": "readonly discovery: Discovery"
          },
          {
            "kind": "property",
            "name": "transport",
            "signature": "readonly transport: Transport"
          },
          {
            "kind": "property",
            "name": "store",
            "signature": "readonly store: Store"
          },
          {
            "kind": "property",
            "name": "agent",
            "signature": "readonly agent: Agent"
          },
          {
            "kind": "method",
            "name": "peers",
            "signature": "@Remote('peers') peers(): PeerInfo[]"
          },
          {
            "kind": "method",
            "name": "checkInbox",
            "signature": "@Remote('checkInbox') checkInbox(): Envelope[]"
          },
          {
            "kind": "method",
            "name": "gateSnapshot",
            "signature": "@Remote('gateSnapshot') gateSnapshot(): Array<GateItem & { id: string }>"
          },
          {
            "kind": "method",
            "name": "approveGate",
            "signature": "@Remote('approveGate') async approveGate(id: string, finalBody?: string): Promise<{ ok: boolean }>"
          },
          {
            "kind": "method",
            "name": "rejectGate",
            "signature": "@Remote('rejectGate') rejectGate(id: string): { ok: boolean }"
          },
          {
            "kind": "method",
            "name": "getProjects",
            "signature": "@Remote('getProjects') getProjects(): ProjectEntry[]"
          },
          {
            "kind": "method",
            "name": "setProjects",
            "signature": "@Remote('setProjects') async setProjects(projects: ProjectEntry[]): Promise<{ ok: boolean }>"
          },
          {
            "kind": "method",
            "name": "importWorkspaces",
            "signature": "@Remote('importWorkspaces') async importWorkspaces(): Promise<{ ok: boolean; added: number }>"
          },
          {
            "kind": "method",
            "name": "nodeStatus",
            "signature": "@Remote('nodeStatus') nodeStatus(): NodeStatus"
          },
          {
            "kind": "method",
            "name": "debugSnapshot",
            "signature": "@Remote('debugSnapshot') debugSnapshot(): DebugSnapshot"
          },
          {
            "kind": "method",
            "name": "send",
            "signature": "async send(target: SendTarget, body: string): Promise<'delivered' | 'queued' | 'offline'>"
          },
          {
            "kind": "method",
            "name": "attachProjectsBridge",
            "signature": "attachProjectsBridge( source: () => ProjectEntry[], persist: (projects: ProjectEntry[]) => Promise<void>, ): void",
            "summary": "Wire the settings-resolved project source + persistence into the service.",
            "jsDoc": "/** Wire the settings-resolved project source + persistence into the service. */"
          },
          {
            "kind": "method",
            "name": "updateProjects",
            "signature": "updateProjects(projects: ProjectEntry[]): void",
            "summary": "Replace the actionable project table + announced names (used by live settings edits).",
            "jsDoc": "/** Replace the actionable project table + announced names (used by live settings edits). */"
          }
        ],
        "types": [
          {
            "name": "Address",
            "declaration": "export interface Address {\n    id?: string;\n    name?: string;\n    capability?: string;\n    group?: string;\n    broadcast?: boolean;\n    project?: string;\n}"
          },
          {
            "name": "Agent",
            "declaration": "export class Agent extends EventEmitter {\n    send(target: SendTarget, body: string, attachment?: AttachmentRef): Promise<'delivered' | 'queued' | 'offline'>;\n    sendAndWait(target: SendTarget, body: string): Promise<SendAndWaitResult>;\n    checkInbox(): Envelope[];\n    gateSnapshot(): Array<GateItem & { id: string; }>;\n    setProjects(projects: ProjectEntry[] | undefined): void;\n    handleInbound(envelope: Envelope): Promise<void>;\n    approveGate(id: string, finalBody?: string): Promise<void>;\n    rejectGate(id: string): void;\n}"
          },
          {
            "name": "AttachmentRef",
            "declaration": "export interface AttachmentRef {\n    filename: string;\n    size: number;\n    hash: string;\n    ref: string;\n}"
          },
          {
            "name": "Discovery",
            "declaration": "export class Discovery extends EventEmitter {\n    start(): void;\n    stop(): void;\n    peers(): PeerInfo[];\n    setProjects(names: string[]): void;\n    resolveById(id: string): PeerInfo | undefined;\n    resolveByName(name: string): PeerInfo | undefined;\n    resolveByCapability(capability: string): PeerInfo[];\n    hasNameConflict(id: string): boolean;\n}"
          },
          {
            "name": "Envelope",
            "declaration": "export interface Envelope {\n    id: string;\n    kind: EnvelopeKind;\n    from: PeerRef;\n    to: Address;\n    replyTo?: string;\n    body: string;\n    attachment?: AttachmentRef;\n    ts: number;\n    auto?: boolean;\n    depth?: number;\n}"
          },
          {
            "name": "EnvelopeKind",
            "declaration": "export type EnvelopeKind = 'request' | 'reply' | 'event';"
          },
          {
            "name": "GateItem",
            "declaration": "export interface GateItem {\n    original: Envelope;\n    draftBody: string;\n}"
          },
          {
            "name": "NodeIdentity",
            "declaration": "export interface NodeIdentity {\n    id: string;\n    name: string;\n}"
          },
          {
            "name": "NodeStatus",
            "declaration": "export interface NodeStatus {\n    host: string;\n    requestedPort: number;\n    effectivePort: number;\n    started: boolean;\n}"
          },
          {
            "name": "WireFrame",
            "declaration": "export interface WireFrame {\n    dir: 'in' | 'out';\n    ts: number;\n    json: string;\n}"
          },
          {
            "name": "DebugSnapshot",
            "declaration": "export interface DebugSnapshot {\n    version: string;\n    debug: boolean;\n    nodeName: string;\n    advertisedHost: string;\n    requestedPort: number;\n    effectivePort: number;\n    started: boolean;\n    frames: WireFrame[];\n    peers: PeerInfo[];\n    outboxCount: number;\n    inboxCount: number;\n    gateCount: number;\n    pendingWaits: number;\n    outboundConnections: number;\n    inboundConnections: number;\n}"
          },
          {
            "name": "OutboxEntry",
            "declaration": "export interface OutboxEntry {\n    peer: PeerAddress;\n    envelope: Envelope;\n    attempts: number;\n}"
          },
          {
            "name": "PeerAddress",
            "declaration": "export interface PeerAddress {\n    host: string;\n    port: number;\n}"
          },
          {
            "name": "PeerInfo",
            "declaration": "export interface PeerInfo {\n    id: string;\n    name: string;\n    capabilities: string[];\n    projects: string[];\n    host: string;\n    port: number;\n    lastSeen: number;\n    manual: boolean;\n}"
          },
          {
            "name": "PeerRef",
            "declaration": "export interface PeerRef {\n    id: string;\n    name: string;\n    host?: string;\n    port?: number;\n}"
          },
          {
            "name": "ProjectEntry",
            "declaration": "export interface ProjectEntry {\n    name: string;\n    path: string;\n    broadcast: boolean;\n}"
          },
          {
            "name": "SendAndWaitResult",
            "declaration": "export type SendAndWaitResult = { status: 'reply'; reply: Envelope; } | { status: 'timeout'; } | { status: 'queued'; };"
          },
          {
            "name": "SendTarget",
            "declaration": "export interface SendTarget {\n    id?: string;\n    name?: string;\n    capability?: string;\n    broadcast?: boolean;\n    project?: string;\n}"
          },
          {
            "name": "Store",
            "declaration": "export class Store extends EventEmitter {\n    send(peer: PeerAddress, envelope: Envelope): Promise<'delivered' | 'queued'>;\n    queueOutgoing(peer: PeerAddress, envelope: Envelope): void;\n    flush(): Promise<number>;\n    outboxSnapshot(): OutboxEntry[];\n    deadLetterSnapshot(): OutboxEntry[];\n    deliverInbound(envelope: Envelope): void;\n    checkInbox(): Envelope[];\n    markThreadRead(peerId: string): void;\n    humanUnreadCount(peerId?: string): number;\n}"
          },
          {
            "name": "Transport",
            "declaration": "export class Transport extends EventEmitter {\n    start(): void;\n    stop(): Promise<void>;\n    send(peer: PeerAddress, envelope: Envelope): Promise<void>;\n}"
          }
        ]
      }
    ],
    "events": [],
    "objects": []
  },
}
